# Generated by Django 4.1.4 on 2023-02-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('hero', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('Hindi', 'Hind'), ('Telgu', 'Telgu'), ('Malyalam', 'Malyalam'), ('English', 'English')], max_length=150)),
            ],
        ),
    ]
