# Generated by Django 4.1.4 on 2023-02-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesDetails',
            fields=[
                ('name_id', models.AutoField(primary_key=True, serialize=False)),
                ('director_name', models.CharField(max_length=100)),
                ('collection', models.CharField(max_length=150)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapi.movies')),
            ],
        ),
    ]
